### ISSUE TITLE
[feature] bhop boost limit

### ISSUE THREAD

**Issue by qberkdc** [bariscodefxy/XGMod#1]
It would be great if the maximum acceleration limit could be added
then we can make strafe to speed up by ourselves
good work XG Team*

**Comment by bariscodefxy** [comment]
Working on it.

**Comment by bariscodefxy** [comment]
Added on commit [6da0155](https://github.com/bariscodefxy/XGMod/commit/6da0155c13916f0f282fe1326b784627945c3bb3).
You can set the limit by 'xg_bhop_boost_limit' cvar.
According to speedometer, the boost won't work if speed > xg_bhop_boost_limit.
